parameters:
#    app_general.example.class: App\GeneralBundle\Example

services:
#    app_general.example:
#        class: %app_general.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
